on:
  push:
    branches: [ master ]
name: Deploy to GitHub Pages
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
          cname: alisoft.dev
          user_name: 'see'
          user_email: 'upcwangying@126.com'
